services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: localhost
      DB_PORT: 13165
      DB_NAME: school_app
      DB_USER: root
      DB_PASS: our_password_redacted_for_security_reasons
